name: CI-Azure Bicep Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: 'komatsu'
      LOCATION: 'eastus'  # Adjust to your region
      FACTORY_NAME: 'ADF033'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: |
          az bicep install
          az bicep upgrade

      - name: Find JSON Files for Linked Services, Datasets, Pipelines
        id: find_files
        run: |
          linkedServiceFiles=$(find ${{ github.workspace }}/linkedServices -name "*.json")
          datasetFiles=$(find ${{ github.workspace }}/datasets -name "*.json")
          pipelineFiles=$(find ${{ github.workspace }}/pipelines -name "*.json")

          linkedServiceFilesStr=$(echo "$linkedServiceFiles" | tr '\n' ',' | sed 's/,$//')
          datasetFilesStr=$(echo "$datasetFiles" | tr '\n' ',' | sed 's/,$//')
          pipelineFilesStr=$(echo "$pipelineFiles" | tr '\n' ',' | sed 's/,$//')

          echo "linkedServiceFiles=$linkedServiceFilesStr" >> $GITHUB_ENV
          echo "datasetFiles=$datasetFilesStr" >> $GITHUB_ENV
          echo "pipelineFiles=$pipelineFilesStr" >> $GITHUB_ENV

      - name: Deploy Bicep Template to Azure
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ${{ github.workspace }}/main.bicep \
            --parameters \
              factoryName=${{ env.FACTORY_NAME }} \
              location=${{ env.LOCATION }} \
              linkedServiceFiles=${{ env.linkedServiceFiles }} \
              datasetFiles=${{ env.datasetFiles }} \
              pipelineFiles=${{ env.pipelineFiles }}
